ProjektAspNetStudia/Models/Database/Chat.cs
using System;
using System.Collections.Generic;

namespace ProjektAspNetStudia.Models.Database
{
    public class Chat
    {
        public int ChatId { get; set; }
        public string ChatName { get; set; }
        public DateTime LastModificationTime { get; set; }
        public ICollection<ChatUser> ChatUsers { get; set; }
        public ICollection<Message> Messages { get; set; }
    }
}

ProjektAspNetStudia/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProjektAspNetStudia.Models;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using ProjektAspNetStudia.Models.ViewModels;
using ProjektAspNetStudia.Utilities;

namespace ProjektAspNetStudia.Controllers
{
    public class HomeController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly AppDbContext _dbContext;

        public HomeController(UserManager<AppUser> userManager, AppDbContext dbContext)
        {
            _dbContext = dbContext;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(string language)
        {
            if (!CultureUtility.SetCurrentThreadCulture(language))
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Chat", "Home", new {chatId = user.CurrentChatId});
            }
            return Redirect($"/{language}/login/signin");
        }
        
        [Route("{language=en-US}/Home/Chat/{chatId?}")]
        public async Task<IActionResult> Chat(string language, int? chatId = null)
        {
            if (!CultureUtility.SetCurrentThreadCulture(language))
            {
                return NotFound();
            }

            if (!HttpContext.User.Identity.IsAuthenticated)
            {
                return StatusCode(403);
            }

            if (chatId.HasValue)
            {
                var userId = _userManager.GetUserId(HttpContext.User);

                var user = _dbContext.Users.FirstOrDefault(u => u.Id == userId);

                if (user != null)
                {
                    user.CurrentChatId = chatId.Value;
                    await _dbContext.SaveChangesAsync();
                }
                else
                {
                    return Error();
                }
            }
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjektAspNetStudia/Views/Shared/Components/ChatPanel/ChatPanelViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ProjektAspNetStudia.Chat;
using ProjektAspNetStudia.Models;

namespace ProjektAspNetStudia.Views.Shared.Components.ChatPanel
{
    public class ChatPanelViewComponent: ViewComponent
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly ChatManager _chatManager;

        public ChatPanelViewComponent(UserManager<AppUser> userManager, ChatManager chatManager)
        {
            _chatManager = chatManager;
            _userManager = userManager;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            System.Diagnostics.Debug.WriteLine($"UserId z componentu: {userId}");
            var messages = await _chatManager.GetChatMessages(userId);
            return View(new ChatPanelModel {Messages = messages, UserId = userId});
        }
    }
}

ProjektAspNetStudia/Views/Shared/Components/RecentChat/RecentChatViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ProjektAspNetStudia.Chat;

namespace ProjektAspNetStudia.Views.Shared.Components.RecentChat
{
    public class RecentChatViewComponent: ViewComponent
    {
        private readonly ChatManager _chatManager;

        public RecentChatViewComponent(ChatManager chatManager)
        {
            _chatManager = chatManager;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var result = await _chatManager.GetChatsForGivenUser(HttpContext.User);
            return View(result);
        }
    }
}

ProjektAspNetStudia/Views/Home/Chat.cshtml
@using ProjektAspNetStudia.Resources
@model ProjektAspNetStudia.Models.ViewModels.RegisterViewModel
@{
    ViewData["Title"] = "Chats";
}

@section Styles
{
    <link rel="stylesheet" href="@Url.Content("~/css/messanger.css")" type="text/css" />
    <link rel="stylesheet" href="@Url.Content("~/css/autocomplete.css")" type="text/css" />
}
<div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <h4 class="modal-title">@Strings.CreateNewRoomModalTitle</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="createRoomRoomName">@Strings.CreateNewRoomModalRoomNameLabel</label>
                        <input type="text" class="form-control" id="createRoomRoomName"/>
                    </div>
                    <div class="form-group">
                        <label for="createRoomSelectedUsers">@Strings.CreateNewRoomModalSelectedUsersLabel</label>
                        <div id="createRoomSelectedUsers" class="new_room_selected_users w-50 px-2 py-1"></div>
                    </div>
                    <div class="form-group">
                        <label for="createRoomUserName">@Strings.CreateNewRoomModalSearchForUsersLabel</label>
                        <input type="text" class="form-control" id="createRoomUserName"/>
                    </div>
                </form>
            </div>

            <div class="modal-footer">
                <button type="button" id="createRoomSendData" class="btn btn-primary" data-dismiss="modal">@Strings.CreateNewRoomModalCreateButtonText</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">@Strings.CreateNewRoomModalCloseButtonText</button>
            </div>

        </div>
    </div>
</div>

<div class="inbox_msg">
    <div class="inbox_people">
        <div class="headind_srch">
            <div class="recent_heading">
                <h4>Chats</h4>
            </div>
            <div class="create_new_room_button_wrapper">
                <button type="button" class="btn create_new_room_button" title="Create new room" data-toggle="modal" data-target="#myModal">
                    <i class="fas fa-folder-plus"></i>
                </button>
            </div>
        </div>
        @await Component.InvokeAsync("RecentChat")
    </div>

    @await Component.InvokeAsync("ChatPanel")
</div>

@section Scripts
{
    <script src="@Url.Content("~/lib/signalr/dist/browser/signalr.js")" ></script>
    <script src="@Url.Content("~/js/autocomplete.js")"></script>
    <script src="@Url.Content("~/js/chat.js")" ></script>
}